### PR TITLE
Client: Add OpenAG features

### LINKED ISSUE #6: +ducktap command
As is known, "+ducktap" came to OpenAg Client. It would be nice to come to the BugfixedHL Client.

### LINKED ISSUE #32: Custom crosshair disappears after the start of demo recording
Proof: 

https://user-images.githubusercontent.com/58108407/114349057-71a5bc80-9b78-11eb-8e69-bee793188e8d.mp4

### PR DESCRIPTION
**Pull request by SmileyAG**
Closes #6, closes #32

- zpecial, so you can copy your AG scripts to HL and have them work without touching anything
- cl_autojump 0/1, again so that you don't have to change your AG scripts
- cl_autojump_priority 0/1, to decide if +jump has priority over ducktap when both are used
- cl_autojump 1 takes priority over cl_jumptype
- +ducktap
- hud_speedometer_below_cross 0/1

### CODE REVIEW

**Comment by tmp64** [comment]
I rebased your branch to include vector refactoring changes I just merged into master

**Comment by tmp64** [comment]
I decided to remove `+bhop` in favor of `cl_autojump 1`.
1) It interferes with `+jump + cl_autojump` and `+ducktap` and I couldn't find a nice way to solve that.
2) Because of how file system in HL works, mods read config.cfg from Half-Life directory on first launch. It is inconvenient because mods will inherit `bind space +bhop` which won't work because they don't have `+bhop`. Players need to manually rebind space back to `+jump`.

**Comment by tmp64** [comment]
I restored the m_pWeapon check so the cursor is hidden when player has no weapons (e.g. in singleplayer before the crowbar). However, I couldn't reproduce the problem (crosshair hiding on record) at all, so can you check that it still doesn't reoccur?

**Comment by SmileyAG** [comment]
> so can you check that it still doesn't reoccur?

With m_pWeapon check this issue still occurs, my other two friends has the same situation.

**Comment by tmp64** [comment]
Thanks!

**Pull request merged**
