### PR TITLE
Linux curl

### PR DESCRIPTION
**Pull request by EzicMan**
Your CI is kinda fuck*d up, so I(and you) tried to fix it

### CODE REVIEW

**Comment by tmp64** [comment]
> Your CI is kinda fuck*d up, so I(and you) tried to fix it
Tell me something I don't know

**Comment by EzicMan** [comment]
>Tell me something I don't know

Did you know that Alfred Hitchcock didn't have a bellybutton?

**Comment by tmp64** [comment]
No, I did not

**Comment by EzicMan** [comment]
>No, I did not

Did you know that we DDoS-ed Ubuntu repositories twice today?

**Comment by EzicMan** [comment]
https://www.youtube.com/watch?v=ozuRmtWQGMU

**Pull request merged**
